name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  flutter: ">=3.13.0"
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sound_fonts:
    path: ..

dev_dependencies:
  build_runner: ^2.6.1
  lints: ^6.0.0
  test: ^1.21.0

dependency_overrides:
  # TODO: Remove when `flutter` from SDK upgrades.
  meta: ^1.17.0
