name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  flutter: ">=3.13.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sound_fonts:
    path: ..

dev_dependencies:
  build_runner: ^2.4.4
  lints: ^2.0.0
  test: ^1.21.0
