builders:
  sound_fonts:
    import: "package:sound_fonts/src/builder.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": ["fonts.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
